FROM node:16-alpine as builder

WORKDIR /app

COPY package*.json ./
# Install with a clean slate
RUN npm ci

COPY . .

RUN npm run build


FROM nginx as nginx

COPY ./ops/nginx.entrypoint.sh ./
COPY ./ops/nginx.default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["./nginx.entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
